### ISSUE TITLE
root required for adb backup?

### ISSUE THREAD

**Issue by straef** [camalot/droidexplorer#65]
i do not have a rooted device and am not in a position to root my device at the moment. however i need to perform a backup right away and know about adb backup and how it does not get all the apps depending on some dev tags.

i broke my phone screen and when i send it for repairs the device will be wiped. so i want to know before-hand what is and is not included in the backup i make so i can ensure at least the important things are safe. this tool was recommended as a way to see inside the backup file.

in the requirements it specifies a rooted device with busybox, but on the creator's blog it states that no root required, at least for making backups. ([blog source](http://blog.twimager.com/2012/08/droid-explorer-0887-backup-feature.html)) but that was for an older version so things may have changed. i know i do not need rooted device to make a normal adb backup with sdk. but i want to make sure before i invest time into setting this software up.

will this work to backup a non-rooted device and examine backup contents?

**Comment by camalot** [comment]
This is the best information source for what is/is not backed up : https://android.stackexchange.com/questions/28296/full-backup-of-non-rooted-devices

**Comment by straef** [comment]
@camalot thank you for the information but that is not what i was asking.

**Comment by camalot** [comment]
You can run a backup, from Droid Explorer on a non-rooted device, that is stated in that link. Droid Explorer just runs the Android Backup. The problem you may have, is that your screen doesn't work. When you run backup, it asks you for an encryption password. 

If your device was rooted, you could use Droid Explorer's ability to (slowly) remote control the device.
