### ISSUE TITLE
DroidExplorer won't open after a few runs

### ISSUE THREAD

**Issue by lolcocks123** [camalot/droidexplorer#66]
I have faced this issue over three times now.

I reinstall Windows, use Droid Explorer a couple of times and after about 10 uses, Droid Explorer stops working.

So the issue is Droid Explorer crashes after trying to connect to the device.
This the last message I see:

![last screen](https://user-images.githubusercontent.com/16006564/39756406-5ab785c6-527e-11e8-9032-8941baf9a14d.png)

After that it just closes, nothing happens.

Here's the log:
https://pastebin.com/fULc333k
(Sorry, but if I post the log here it's causing some formatting issues.)

Today afternoon, I reinstalled Windows 10 x64 Build 17134.1 (that's the April 2018 update), installed Droid Explorer, used it about 5 times.
Stopped working after that.

Can someone please help me out?

**Comment by camalot** [comment]
does it actually close or is the icon still in the task bar like the app is running?

Try going into  `C:\Users\<UserName>\AppData\Roaming\DroidExplorer` and delete everything in there.

**Comment by lolcocks123** [comment]
Thank you @camalot, it worked.
I deleted only the assets folder. It had generated way too many thumbnails of the files in my phone which was causing the crash.
