### ISSUE TITLE
What SDK path does the app need?

### ISSUE THREAD

**Issue by aruku** [camalot/droidexplorer#67]
I've been trying for quite a while, and I've not been able to figure out what exact SDK path the installer wants.
I downloaded just the SDK and installed Android Studio and have it download the SDK as a dependency.
Nothing worked.

**Comment by VasylDyakun** [comment]
As a workaround you can download the latest SDK but replace platform tools of the older version: v.26.0 that should fix your issue.
Details are here: https://github.com/camalot/droidexplorer/issues/63

**Comment by aruku** [comment]
Thank you!
