### ISSUE TITLE
How to install "droidexplorer" without Android Studio!

### ISSUE THREAD

**Issue by Msadr471** [camalot/droidexplorer#84]
Hi,

is there any way to install it without Android Studio? Because I don't know why its keep saying “Android SDK Invalid”
![image](https://user-images.githubusercontent.com/49529241/156657795-cc5b7809-5be4-4903-8696-a1e0f6220c9c.png)
And what is Android SDK? Is it this one? 
![image](https://user-images.githubusercontent.com/49529241/156657987-1e92dc27-bc05-4db4-a2e9-ce282cea78e6.png)
or this one?
![image](https://user-images.githubusercontent.com/49529241/156658063-aeccbb71-582f-4ff1-9f78-fd4d22b51511.png)
please help me, I'm a newbie.

**Comment by biggestsonicfan** [comment]
At this point I'd advise against using Droid Explorer given it's age and probably growing issues as other software has developed and changed over time. The software is not actively receiving support.

**Comment by Msadr471** [comment]
> At this point I'd advise against using Droid Explorer given it's age and probably growing issues as other software has developed and changed over time. The software is not actively receiving support.

So, do you have any idea how to extract a “backup.ab” file? 
I want to remove “com.sec.hearingadjust” from this backup, and then restore it.

**Comment by biggestsonicfan** [comment]
So, you don't want to install Android Studio but the backup was created with `adb backup`, alright, bizzare flex but sure.

You could try [Android Backup Extractor](https://github.com/nelenkov/android-backup-extractor), which has an unpack and pack option.
